runtime: go
api_version: go1

handlers:

- url: /google74caec1abcbbe3ab.html
  static_files: static/google74caec1abcbbe3ab.html
  upload: static/google74caec1abcbbe3ab.html

- url: /static
  static_dir: static

- url: /worker/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app

error_handlers:
  - file: static/html/error/default.html

  - error_code: over_quota
    file: static/html/error/overQuota.html
