runtime: go
api_version: go1

inbound_services:

  - warmup

handlers:

  - url: /favicon.ico
    static_files: static/i/favicon.ico
    upload: static/i/favicon.ico

  - url: /static
    static_dir: static

  - url: /_ah/warmup
    script: _go_app
    login: admin

  - url: /worker/.*
    script: _go_app
    login: admin

  - url: /.*
    script: _go_app

error_handlers:

  - file: static/html/error/default.html

  - error_code: over_quota
    file: static/html/error/overQuota.html
